"""add rajaongkir_id to cities

Revision ID: 14f712e39967
Revises: d17833179374
Create Date: 2026-04-27 02:51:57.681879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f712e39967'
down_revision: Union[str, Sequence[str], None] = 'd17833179374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('rajaongkir_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'rajaongkir_id')
    # ### end Alembic commands ###
