"""Add subdistricts and enriched tracking data

Revision ID: d17833179374
Revises: a2a881502525
Create Date: 2026-04-25 00:57:02.440327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17833179374'
down_revision: Union[str, Sequence[str], None] = 'a2a881502525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdistricts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdistricts_id'), 'subdistricts', ['id'], unique=False)
    op.add_column('tracking', sa.Column('service_type', sa.String(), nullable=True))
    op.add_column('tracking', sa.Column('weight_gram', sa.Integer(), nullable=True))
    op.add_column('tracking', sa.Column('length_cm', sa.Integer(), nullable=True))
    op.add_column('tracking', sa.Column('width_cm', sa.Integer(), nullable=True))
    op.add_column('tracking', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.add_column('tracking', sa.Column('insurance_value', sa.Float(), nullable=True))
    op.add_column('tracking', sa.Column('shipping_cost', sa.Float(), nullable=True))
    op.add_column('tracking', sa.Column('sender_address', sa.String(), nullable=True))
    op.add_column('tracking', sa.Column('sender_postal_code', sa.String(), nullable=True))
    op.add_column('tracking', sa.Column('sender_lat', sa.Float(), nullable=True))
    op.add_column('tracking', sa.Column('sender_long', sa.Float(), nullable=True))
    op.add_column('tracking', sa.Column('receiver_postal_code', sa.String(), nullable=True))
    op.add_column('tracking', sa.Column('receiver_lat', sa.Float(), nullable=True))
    op.add_column('tracking', sa.Column('receiver_long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking', 'receiver_long')
    op.drop_column('tracking', 'receiver_lat')
    op.drop_column('tracking', 'receiver_postal_code')
    op.drop_column('tracking', 'sender_long')
    op.drop_column('tracking', 'sender_lat')
    op.drop_column('tracking', 'sender_postal_code')
    op.drop_column('tracking', 'sender_address')
    op.drop_column('tracking', 'shipping_cost')
    op.drop_column('tracking', 'insurance_value')
    op.drop_column('tracking', 'height_cm')
    op.drop_column('tracking', 'width_cm')
    op.drop_column('tracking', 'length_cm')
    op.drop_column('tracking', 'weight_gram')
    op.drop_column('tracking', 'service_type')
    op.drop_index(op.f('ix_subdistricts_id'), table_name='subdistricts')
    op.drop_table('subdistricts')
    # ### end Alembic commands ###
